#
# Makefile for MediaLB driver test app.

INC += -I$(LINUXPATH)/include

OBJS = $(OBJDIR)/mxc_mlb_test.out

all : $(OBJS)

.PHONY: clean
clean :
	rm -f $(OBJS)

#
# include the Rules
#
include ../make.rules
