#! /bin/bash

echo "extend u-boot to 0x2F000..."
objcopy -I binary -O binary --pad-to 0x2f000 --gap-fill=0x5a u-boot.bin u-boot-pad.bin

echo "generate csf data..."
../linux/cst --o u-boot_csf.bin < u-boot.csf

echo "merge image and csf data..."
cat u-boot-pad.bin u-boot_csf.bin > u-boot-signed.bin

echo "extend final image to 0x31000..."
objcopy -I binary -O binary --pad-to 0x31000 --gap-fill=0x5a u-boot-signed.bin u-boot-signed-pad.bin

echo "u-boot-signed-pad.bin is ready"
