#! /usr/bin/perl -w
use strict;

open(my $out, '>:raw', 'ivt.bin') or die "Unable to open: $!";
print $out pack("V", 0x402000D1);	# Signature
print $out pack("V", 0x10801000);	# Jump Location
print $out pack("V", 0x0);		# Reserved
print $out pack("V", 0x0);		# DCD pointer
print $out pack("V", 0x0);		# Boot Data
print $out pack("V", 0x10BFDFE0);	# Self Pointer
print $out pack("V", 0x10BFE000);	# CSF Pointer
print $out pack("V", 0x0);		# Reserved
close($out);
