#*****************************************************************************
#
# makefile for dryice test program
#
#****************************************************************************/
OBJS = $(OBJDIR)/dryice.sh

all : $(OBJS)

.PHONY: clean
clean :
	rm -f $(OBJS)

#
# include the Rules
#
include ../make.rules
