#! /bin/bash

echo "extend boot.img to %pad_len%..."
objcopy -I binary -O binary --pad-to %pad_len% --gap-fill=0x5A boot.img boot-pad.img

echo "generate IVT"
./genIVT

echo "attach IVT..."
cat boot-pad.img ivt.bin > boot-pad-ivt.img

echo "generate csf data..."
../linux/cst --o bootimg_csf.img < bootimg.csf

echo "merge image and csf data..."
cat boot-pad-ivt.img bootimg_csf.img > boot-signed.img

echo "extend final image to %sig_len%..."
objcopy -I binary -O binary --pad-to %sig_len% --gap-fill=0x5A boot-signed.img boot-signed-pad.img
