#! /bin/bash

echo "extend zImage to %pad_len%..."
objcopy -I binary -O binary --pad-to %pad_len% --gap-fill=0x5A zImage zImage-pad.bin

echo "generate IVT"
./genIVT

echo "attach IVT..."
cat zImage-pad.bin ivt.bin > zImage-pad-ivt.bin

echo "generate csf data..."
../linux/cst --o zImage_csf.bin < zImage.csf

echo "merge image and csf data..."
cat zImage-pad-ivt.bin zImage_csf.bin > zImage-signed.bin

echo "extend final image to %sig_len%..."
objcopy -I binary -O binary --pad-to %sig_len% --gap-fill=0x5A zImage-signed.bin zImage-signed-pad.bin
